# Generated by Django 3.2.7 on 2021-10-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_notepost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepost',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
